### ISSUE TITLE
Add a command that allows you to set a category that #mafia-game-night appears in

### ISSUE THREAD

**Issue by ZachieBlade** [dylanpiera/Mafia-Quickplay-DiscordBot#77] opened 2017-10-02 14:49 UTC

**Comment by dylanpiera** [comment] 2017-10-02 15:06
Duplicate of #62 

Due to current limitations of the Discord.Net api this is impossible. Will be added as soon as it's possible.

**Closed as completed by dylanpiera** 2017-10-02 15:06 UTC
Labels: duplicate, Maybe Later
