### ISSUE TITLE
Cop scans do not appear to be working

### ISSUE THREAD

**Issue by AussieEevee** [dylanpiera/Mafia-Quickplay-DiscordBot#58] opened 2017-09-27 12:31 UTC
![img_20170927_175145_034](https://user-images.githubusercontent.com/26673976/30913463-e2db8f58-a3c2-11e7-8619-21d6c8503b7f.jpg)

**Comment by dylanpiera** [comment] 2017-09-27 12:34
Please note that the cop scan is working as intended, it is just not showing the target correctly. Will be fixed in next update 👍

**Closed as completed** 2017-09-27 13:37 UTC
Labels: bug
